[package]
name = "node-enigo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
enigo = "0.3.0"
napi = { version = "2.12.2", features = ["tokio_rt"] }
napi-derive = "2.12.2"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
napi-build = "2.0.1"
